[package]
name = "toolbox"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
iced = { version = "0.14.0", features = ["tokio", "sipper"] }
open = "5.3.3"
rfd = "0.17.2"
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["rt"] }
